name: Auto-Compile AHK
on: [push] # Запускать сборку при каждом обновлении кода

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compile AHK to EXE
        uses: logicxd/ahk-compiler-action@v2
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          script: "VimCapslockArrows.ahk" # Название вашего файла из скриншота

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Compiled-Script
          path: VimCapslockArrows.exe
