name: Build and Release
on:
  push:
    branches:
      - main  # Запускать при каждом пуше в основную ветку

permissions:
  contents: write # ЭТО ВАЖНО: разрешает экшену создавать релизы

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile AHK Script
        uses: CCCC-L/Action-Ahk2Exe@main # Специальный экшен для AHK v2
        with:
          in: Vim-CapsLock-arrows.ahk
          out: Vim-CapsLock-arrows.exe

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: Vim-CapsLock-arrows.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
